[project]
name = "self-cite-checker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "pandas>=2.2.3",
    "scholarly>=1.7.11",
    "selenium>=4.32.0",
    "tqdm>=4.67.1",
]
